# SPDX-FileCopyrightText: 2025 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

### COMMAND
  - type: department
    id: StellarDepartmentCommand
    name: stellar-department-name-command
    description: stellar-department-description-command
    color: "#334E6D"
    roles:
    - StellarJobCommandCaptain
    - StellarJobCommandOperationsManager
    - StellarJobCommandChiefEngineer
    - StellarJobCommandServiceDirector
    - StellarJobCommandResearchDirector
    - StellarJobCommandHeadOfMedicine
    - StellarJobCommandHeadOfSecurity
    primary: false
    weight: 2

### SUPPLY
  - type: department
    id: StellarDepartmentSupply
    name: stellar-department-name-supply
    description: stellar-department-description-supply
    color: "#A46106"
    roles:
    - StellarJobSupplyJanitor
    - StellarJobSupplyHandler
    - StellarJobSupplyCourier
    - StellarJobCommandOperationsManager # Command

### SERVICE
  - type: department
    id: StellarDepartmentService
    name: stellar-department-name-service
    description: stellar-department-description-service
    color: "#9FED58"
    weight: -1
    roles:
    - StellarJobServiceBartender
    - StellarJobServiceBotanist
    - StellarJobServiceCleric
    - StellarJobServiceChef
    - StellarJobServicePerformer
    - StellarJobServiceLibrarian
    - StellarJobServiceReporter
    - StellarJobServiceAssistant
    - StellarJobCommandServiceDirector # Command

### SCIENCE
  - type: department
    id: StellarDepartmentScience
    name: stellar-department-name-science
    description: stellar-department-description-science
    color: "#D381C9"
    roles:
    - StellarJobScienceScientist
    - StellarJobCommandResearchDirector # Command

### SECURITY
  - type: department
    id: StellarDepartmentSecurity
    name: stellar-department-name-security
    description: stellar-department-description-security
    color: "#DE3A3A"
    weight: 1
    roles:
    - StellarJobSecurityOfficer
    - StellarJobSecurityDetective
    - StellarJobSecurityWarden
    - StellarJobCommandHeadOfSecurity # Command

### MEDICAL
  - type: department
    id: StellarDepartmentMedical
    name: stellar-department-name-medical
    description: stellar-department-description-medical
    color: "#52B4E9"
    roles:
    - StellarJobMedicalChemist
    - StellarJobMedicalDoctor
    - StellarJobMedicalPsychologist
    - StellarJobMedicalParamedic
    - StellarJobCommandHeadOfMedicine # Command

### ENGINEERING
  - type: department
    id: StelalrDepartmentEngineering
    name: stellar-department-name-engineering
    description: stellar-department-description-engineering
    color: "#EFB341"
    roles:
    - StellarJobEngineeringEngineer
    - StellarJobCommandChiefEngineer # Command

### SILICON
  - type: department
    id: StellarDepartmentSilicon
    name: stellar-department-name-silicon
    description: stellar-department-description-silicon
    color: "#D381C9"
    roles:
    - Borg
    - StationAi # Command
    weight: -2

### INTERN
  - type: department
    id: StellarDepartmentIntern
    name: stellar-department-name-intern
    description: stellar-department-description-intern
    color: "#bbbbbb"
    roles:
    - StellarJobInternEngineering
    - StellarJobInternMedical
    - StellarJobInternScience
    - StellarJobInternSecurity
    - StellarJobInternSupply
    weight: -3
