# SPDX-FileCopyrightText: 2025 AftrLite
#
# SPDX-License-Identifier: LicenseRef-Wallening

### UNIFORMS
- type: entity
  parent: ClothingUniformBase
  id: StellarClothingUniformCommandHeadOfSecurity
  name: head of security's uniform
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform.rsi
  - type: Clothing
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform.rsi

- type: entity
  parent: StellarClothingUniformCommandHeadOfSecurity
  id: StellarClothingUniformCommandHeadOfSecuritySkirt
  name: head of security's uniform & skirt
  description: LOREM IPSUM
  components:
  - type: Clothing
    slots: [innerclothing]
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING-skirt

- type: entity
  parent: ClothingUniformBase
  id: StellarClothingUniformCommandHeadOfSecurityAlt
  name: head of security's alternate uniform
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-alt.rsi
  - type: Clothing
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-alt.rsi

- type: entity
  parent: StellarClothingUniformCommandHeadOfSecurityAlt
  id: StellarClothingUniformCommandHeadOfSecurityAltSkirt
  name: head of security's alternate uniform & skirt
  description: LOREM IPSUM
  components:
  - type: Clothing
    slots: [innerclothing]
    clothingVisuals:
      jumpsuit:
      - state: equipped-INNERCLOTHING-skirt

- type: entity
  parent: ClothingUniformBase
  id: StellarClothingUniformCommandHeadOfSecurityFormal
  name: head of security's formals
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-formal.rsi
  - type: Clothing
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-formal.rsi

- type: entity
  parent: ClothingUniformBase
  id: StellarClothingUniformCommandHeadOfSecurityParade
  name: head of security's parade uniform
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-parade.rsi
  - type: Clothing
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-uniform-parade.rsi

### HATS
- type: entity
  parent: ClothingHeadBase
  id: StellarClothingHatCommandHeadOfSecurityBeret
  name: head of security's beret
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-hat-beret.rsi
  - type: Clothing
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-hat-beret.rsi
  - type: Item
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-hat-beret.rsi
  - type: Tag
    tags:
    - ClothMade
    - Recyclable


### BACKPACKS
- type: entity
  parent: [ClothingBackpack, BaseCommandContraband]
  id: StellarClothingBackpackCommandHeadOfSecurity
  name: head of security's backpack
  description: LOREM IPSUM
  components:
  - type: Sprite
    sprite: _ST/Clothing/Command/HeadOfSecurity/headofsecurity-backpack.rsi
